[package]
name = "radix-leptos-use-previous"
description = "Leptos port of Radix Use Previous."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
